---
# variables:
#   WORKON_HOME: "$CI_PROJECT_DIR/nikola/.cache/venvs"
#   PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/nikola/.cache/pipenv"
# cache:
#   paths:
#     - ember/node_modules
#     - ember/dist
#     - middleman/vendor/ruby
#     - middleman/build
#     - nikola/output
#     - nikola/.cache

build-ember:
  image: node:14
  stage: build
  before_script:
    - cd ember
    - time npm install
  script:
    - npm run build

build-jekyll:
  image: ruby:3
  stage: build
  before_script:
    - cd jekyll
    - bundle config set path 'vendor'
    - time bundle install
  script:
    - bundler exec jekyll build

build-nikola:
  image: python:3.9
  stage: build
  before_script:
    - pip install pipenv
    - cd nikola
    - time pipenv sync --bare --dev
  script:
    - pipenv run nikola build
