---
build-ember:
  image: node:14
  stage: build
  before_script:
    - cd ember
    - time npm install
  script:
    - npm run build

build-jekyll:
  image: ruby:3
  stage: build
  before_script:
    - cd jekyll
    - bundle config set path 'vendor'
    - time bundle install
  script:
    - bundler exec jekyll build

build-nikola:
  image: python:3.9
  stage: build
  before_script:
    - pip install pipenv
    - cd nikola
    - time pipenv sync --bare --dev
  script:
    - pipenv run nikola build
