---
variables:
  WORKON_HOME: "$CI_PROJECT_DIR/nikola/.cache/venvs"
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/nikola/.cache/pipenv"

# if you want to use npm ci instead of npm install, you will
# need to override npm's cache so it is relative to the build dir
# ex: `npm ci --cache .npm`
build-ember:
  image: node:14
  stage: build
  cache:
    paths:
      - ember/node_modules
  before_script:
    - cd ember
    - time npm install
  script:
    - npm run build

build-jekyll:
  image: ruby:3
  stage: build
  cache:
    paths:
      - jekyll/vendor/ruby
  before_script:
    - cd jekyll
    - bundle config set path "vendor"
    - time bundle install
  script:
    - bundler exec jekyll build

build-nikola:
  image: python:3.9
  stage: build
  cache:
    paths:
      - nikola/.cache
  before_script:
    - pip install pipenv
    - cd nikola
    - time pipenv sync --bare --dev
  script:
    - pipenv run nikola build
